config/routes.rb
Rails.application.routes.draw do
  root 'monitor#index'
  get 'monitor/index'
  resources :events
  resources :devices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :device
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: %i[ show edit update destroy ]

  # GET /devices or /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1 or /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices or /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: "Device was successfully created." }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1 or /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: "Device was successfully updated." }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1 or /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: "Device was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def device_params
      params.require(:device).permit(:device_id, :device_name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:device_id, :event_datetime, :temparature, :humidity, :illumination, :movement)
    end
end

app/controllers/monitor_controller.rb
class MonitorController < ApplicationController
  def index
    @devices = Device.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/monitor_helper.rb
module MonitorHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
        <% device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id %>
  </div>

  <div class="field">
    <%= form.label :device_name %>
    <%= form.text_field :device_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Device name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.device_id %></td>
        <td><%= device.device_name %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @device.device_id %>
</p>

<p>
  <strong>Device name:</strong>
  <%= @device.device_name %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id %>
  </div>

  <div class="field">
    <%= form.label :event_datetime %>
    <%= form.datetime_select :event_datetime %>
  </div>

  <div class="field">
    <%= form.label :temparature %>
    <%= form.text_field :temparature %>
  </div>

  <div class="field">
    <%= form.label :humidity %>
    <%= form.text_field :humidity %>
  </div>

  <div class="field">
    <%= form.label :illumination %>
    <%= form.text_field :illumination %>
  </div>

  <div class="field">
    <%= form.label :movement %>
    <%= form.text_field :movement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Event datetime</th>
      <th>Temparature</th>
      <th>Humidity</th>
      <th>Illumination</th>
      <th>Movement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.device_id %></td>
        <td><%= event.event_datetime %></td>
        <td><%= event.temparature %></td>
        <td><%= event.humidity %></td>
        <td><%= event.illumination %></td>
        <td><%= event.movement %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @event.device_id %>
</p>

<p>
  <strong>Event datetime:</strong>
  <%= @event.event_datetime %>
</p>

<p>
  <strong>Temparature:</strong>
  <%= @event.temparature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @event.humidity %>
</p>

<p>
  <strong>Illumination:</strong>
  <%= @event.illumination %>
</p>

<p>
  <strong>Movement:</strong>
  <%= @event.movement %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benjamin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monitor/index.html.erb
<h1>Nature Remo Monitor</h1>

<h2>Devices</h2>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each_with_index do |device, i| %>
      <tr>
        <td><%= (i+1) %></td>
        <td><%= device.device_id %></td>
        <td><%= device.device_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Temparature</h2>
<%= line_chart Event.group(:device_id).group_by_hour(:event_datetime).average(:temparature) %>
<%# <%= line_chart @events.map { |event|
  {name: event.device.device_name, data: event.group_by_hour(:event_datetime).average(:temparature)}
} %>

<h2>Humidity</h2>
<%= line_chart Event.group(:device_id).group_by_hour(:event_datetime).average(:humidity) %>

<h2>Illumination</h2>
<%= line_chart Event.group(:device_id).group_by_hour(:event_datetime).average(:illumination) %>

<h2>Movement</h2>
<%= line_chart Event.group(:device_id).group_by_hour(:event_datetime).average(:movement) %>